server:
  port: 9003
  servlet:
    context-path: /file

spring:
  application:
    name: online-course-file
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置 Nacos 地址
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

file:
  domain: http://127.0.0.1:9000/file/f/
  path: D:/fileUpload/imooc/

oss:
  accessKeyId: LTAI4G531JhMJPxEmukmA7Yc
  accessKeySecret: GlRP7Z3kGTQ0YnubejJ7WiwEHtSVAu
  endpoint: oss-cn-hangzhou.aliyuncs.com
  bucket: online-course-top
  domain: http://online-course-top.oss-cn-hangzhou.aliyuncs.com/

vod:
  accessKeyId: LTAI4G9mJMU4jkeMGVPTbCsA
  accessKeySecret: 2xK9ogegMnQGqvcCObsJwpmT67JzOQ
