server:
  port: 9000

spring:
  application:
    name: online-course-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置 Nacos 地址
    # 路由转发: 意思是只要是以 /system 开头的路径都转发到 9001: 这样就可以做到对外隐藏,表面上访问的是 9000 实际上是 9001
    gateway:
      routes:
        - id: system
          uri: lb://online-course-system
          predicates:
            - Path=/system/**
        - id: business
          uri: lb://online-course-business
          predicates:
            - Path=/business/**
        - id: file
          uri: lb://online-course-file
          predicates:
            - Path=/file/**
      # 全局跨域
      globalcors:
        # 跨域配置(可以在代码里面处理允许跨域，也可在这里全局处理)
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - DELETE
              - PUT
              - HEAD
              - PATCH