server:
  port: 9001
  servlet:
    context-path: /system

spring:
  application:
    name: online-course-system
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置 Nacos 地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/online_course?characterEncoding=UTF8&useUnicode=false&serverTimezone=UTC
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com:
      lsu:
        system:
          mapper: trace