server:
  port: 9000

spring:
  application:
    name: online-course-system
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置 Nacos 地址
management:
  endpoints:
    web:
      exposure:
        include: '*'